#!/usr/bin/env ruby

require 'find'
require 'logger'

# This script import all handhq source which is under raw_data directory.
# Becareful not to include space character in handhq source file like below
# raw_data/10/abs NLH handhq_5-OBFUSCATED.txt.
# Run below command in source directory will replace space character with under score
# for f in *\ *; do mv "$f" "${f// /_}"; done

src_dir_path = File.join(File.expand_path(File.dirname($0)), "..", "..", "raw_data")
script_path = File.join(File.expand_path(File.dirname($0)), "_import_data_to_mysql.rb")
log_path = File.join(File.expand_path(File.dirname($0)), "..", "..", "log", "import", "#{Time.now.to_i}.log")
log = Logger.new(log_path)

start_time = Time.now
Find.find(src_dir_path) { |file|
  next unless FileTest.file?(file) && file.match(/.*handhq.*txt$/)
  log.info "Start importing file [#{file}] ..."
  log.info `ruby #{script_path} #{file}`
  log.info "Finished importing file [#{file}]\n"
}
finish_time = Time.now
log.info "Execution time : #{finish_time - start_time} (s)"

# Notify finish of script by terminal-notifier
`terminal-notifier -title 'HandHQReader' -message 'Finished' -sound Glass -open '#{log_path}'`
